# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb60d2318ca93674525ab55b3adb253e"
name = "AI Assistant Chat"
handle = "ai-assistant-chat"
application_url = "https://chitchat.iovistacommerce.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,write_products"

[auth]
redirect_urls = ["https://chitchat.iovistacommerce.com/auth/callback", "https://chitchat.iovistacommerce.com/auth/shopify/callback", "https://chitchat.iovistacommerce.com/api/auth/callback"]

[pos]
embedded = false
